### ISSUE TITLE
Check applyFolds for scalar response

### ISSUE THREAD

**Issue by davidruegamer** [fdboost/FDboost#5]
applyFolds does not correctly handle matrices 
```
data("fuelSubset", package = "FDboost")

# center the functional covariates per observed wavelength
fuelSubset$UVVIS <- scale(fuelSubset$UVVIS, scale = FALSE)
fuelSubset$NIR <- scale(fuelSubset$NIR, scale = FALSE)

# fit the scalar-on-function regression model 
sof <- FDboost(heatan ~ bbs(h2o, df = 4) 
               + bsignal(UVVIS, uvvis.lambda, knots = 40, df = 4) 
               + bsignal(NIR, nir.lambda, knots = 40, df = 4), 
               timeformula = NULL, data = fuelSubset)


test <- applyFolds(sof)
```
The error occures because UVVIS and other matrices are defined as long variables and handed over as such to reweightData, which then generates a wrong new data set.

Also: fitfct in applyFolds does not need / use oobweights
https://github.com/fdboost/FDboost/blob/master/R/crossvalidation.R#L176
Bug? Just remove it?

**Comment by sbrockhaus** [comment]
Is it possible that the error in `applyFolds()` occurs because of the scalar response? Because for models with functional response and functional covariates, `applyFolds()` works just fine. 
I think, I never tested `applyFolds()` for scalar response as in this case one can simply use `cvrisk()`. 

And yes, if the fitfct() does not use this argument, it can be deleted.

**Comment by davidruegamer** [comment]
Hmm... I think I just found the error. 
https://github.com/fdboost/FDboost/blob/master/R/crossvalidation.R#L125
`NROW` has to be replaced with `length`. Doing so seems to solve the problem. Also makes sense to me, since id is in fact equal to number of rows for a matrix, but the matrix variable is not in the long format. 
But I find it somehow curious... have we never tested the signal-baselearner with applyFolds?

**Comment by sbrockhaus** [comment]
well, the following code including `bsginal()` works just fine:

```
require(fda)

data("CanadianWeather", package = "fda")
CanadianWeather$l10precip <- t(log(CanadianWeather$monthlyPrecip))
CanadianWeather$temp <- t(CanadianWeather$monthlyTemp)
CanadianWeather$region <- factor(CanadianWeather$region)
CanadianWeather$month.s <- CanadianWeather$month.t <- 1:12

## center the temperature curves per time-point
CanadianWeather$temp <- scale(CanadianWeather$temp, scale = FALSE)
rownames(CanadianWeather$temp) <- NULL ## delete row-names

## fit model with cyclic splines over the year
mod3 <- FDboost(l10precip ~ bsignal(temp, month.s, knots = 11, cyclic = TRUE, 
                          df = 2.5, boundary.knots = c(0.5,12.5), check.ident = FALSE), 
                timeformula = ~ bbs(month.t, knots = 11, cyclic = TRUE, 
                                    df = 3, boundary.knots = c(0.5, 12.5)), 
                offset = "scalar", offset_control = o_control(k_min = 5), 
                data = CanadianWeather) 


#### find the optimal mstop over 5-fold bootstrap 
## using the function applyFolds 
set.seed(456)
folds3 <- cv(rep(1, length(unique(mod3$id))), B = 5)
appl3 <- applyFolds(mod3, folds = folds3)

## look at result
appl3

```

**Comment by sbrockhaus** [comment]
in `all_effectsTEST.R`, we only test applyFolds() for functional response, NOT for scalar response with the following comment:

>  applyFolds() suited to functional response

**Comment by davidruegamer** [comment]
You are right :+1:  In the case we ever want to use `applyFolds` for scalar response -> it does not seem to be that additional much effort.

**Comment by davidruegamer** [comment]
It seems, that we actually need `applyFolds` for scalar response for the bootstrap CIs...

The problem is that by the way `cvrisk` uses weights for resampling, the inner and outer fold in the nested bootstrap-CI-procedure interact with each other and the bootCI function crashes due to inappropriate weights most of the time. 
Using `applyFolds` for the outer loop does not really slow down things, but due to the fact, that `reweightData` constructs a new data set rather than using the weights, the problem of interacting `weights` is solved and the inner loop can be efficiently calculated with `cvrisk` for scalar response.

I would therefore suggest the fix I mentioned in the previous comment (+ further checking, if everything else is fine).

OT: @sbrockhaus : first version of the bootstrap function in your mail box

**Comment by sbrockhaus** [comment]
👍

**Comment by davidruegamer** [comment]
Seems to work.
